package addtodictionary;

import dict.entity.Entries;
import dict.util.HibernateUtil;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author csc
 */
public class mainWindow extends javax.swing.JFrame {


    public mainWindow() {

        initComponents();
        deleteAllbtn.setEnabled(false);
        outputTableConf();
       List full = getHQLQuery(QUERY_FULL);
        totalWordslbl.setText("Total words: " + full.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contextMenuPop = new javax.swing.JPopupMenu();
        Panel1 = new javax.swing.JPanel();
        titlelbl = new javax.swing.JLabel();
        totalWordslbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        introText = new javax.swing.JTextArea();
        addToDict = new javax.swing.JButton();
        getDBdata = new javax.swing.JButton();
        addedlbl = new javax.swing.JLabel();
        updateTablebtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableIn = new javax.swing.JTable();
        deleteAllbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        contextMenuPop.setInheritsPopupMenu(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Dictionary");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(getIcon());

        Panel1.setBackground(new java.awt.Color(51, 51, 51));
        Panel1.setForeground(new java.awt.Color(255, 255, 255));

        titlelbl.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        titlelbl.setForeground(new java.awt.Color(0, 102, 102));
        titlelbl.setText("PERSONAL DICTIONARY");

        totalWordslbl.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        totalWordslbl.setForeground(new java.awt.Color(255, 102, 102));
        totalWordslbl.setText("Words in dictionary:");

        introText.setColumns(20);
        introText.setRows(5);
        introText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                introTextMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(introText);

        addToDict.setText("Add to list");
        addToDict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToDictActionPerformed(evt);
            }
        });

        getDBdata.setText("Get Data from DB");
        getDBdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getDBdataMouseClicked(evt);
            }
        });

        addedlbl.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        addedlbl.setForeground(new java.awt.Color(153, 255, 153));
        addedlbl.setText("Words added:");

        updateTablebtn.setText("Update table");
        updateTablebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTablebtnMouseClicked(evt);
            }
        });

        table.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        table.setForeground(new java.awt.Color(6, 60, 60));
        table.setModel(getTableModel());
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setColumnSelectionAllowed(true);
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        tableIn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Word", "Definition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableIn.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableIn.setColumnSelectionAllowed(true);
        tableIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInMouseClicked(evt);
            }
        });
        tableIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableInKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tableIn);
        tableIn.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tableIn.getColumnModel().getColumn(0).setResizable(false);
        tableIn.getColumnModel().getColumn(0).setPreferredWidth(70);
        tableIn.getColumnModel().getColumn(1).setResizable(false);
        tableIn.getColumnModel().getColumn(1).setPreferredWidth(70);

        deleteAllbtn.setText("DEL");
        deleteAllbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAllbtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Word - Definition");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(titlelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getDBdata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteAllbtn))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(totalWordslbl)
                                .addGap(63, 63, 63))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addGroup(Panel1Layout.createSequentialGroup()
                                                    .addComponent(updateTablebtn)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(addToDict))
                                                .addComponent(jScrollPane1))
                                            .addGroup(Panel1Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel1))))
                                    .addGroup(Panel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(addedlbl)))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlelbl)
                    .addComponent(getDBdata, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAllbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addToDict)
                            .addComponent(updateTablebtn))
                        .addGap(18, 18, 18)
                        .addComponent(totalWordslbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addedlbl)
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addToDictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToDictActionPerformed
        TreeSet<Entries> entries = new TreeSet<Entries>(getHQLQuery(QUERY_FULL));
        TreeSet<Entries> newEntries = new TreeSet<Entries>();
        for (int i = 0; i < tableIn.getRowCount(); i++) {
            boolean filled = tableIn.getValueAt(i, 0) != null && !tableIn.getValueAt(i, 0).toString().trim().equals("");
            if (filled) {
                Object valueAtWord = tableIn.getValueAt(i, 0);
                Object valueAtDef = tableIn.getValueAt(i, 1);
                String word = "";
                String def = "";
                char[] wordArr = valueAtWord.toString().trim().toCharArray();
                char first = Character.toUpperCase(wordArr[0]);
                word = first + valueAtWord.toString().trim().substring(1).toLowerCase().replace("_", " ");
                if (valueAtDef != null && valueAtDef.toString().trim().equals("")) {
                    char[] defArr = valueAtDef.toString().trim().toCharArray();
                    char firstDef = Character.toUpperCase(defArr[0]);
                    def = firstDef + valueAtDef.toString().trim().substring(1).toLowerCase().replace("_", " ");
                }
                newEntries.add(new Entries(word, 0, def));
            }
        }

        String[] txtBoxEntry = introText.getText().split("\\r?\\n");

        for (int i = 0; i < txtBoxEntry.length; i++) {
            String[] text = txtBoxEntry[i].split("-");
            if (!text[0].equals("")) {
                char first = Character.toUpperCase(text[0].trim().charAt(0));
                char firstDef = Character.toUpperCase(text[1].trim().charAt(0));
                String word = first + text[0].trim().substring(1).toLowerCase().replace("_", " ");
                String def = firstDef + text[1].trim().substring(1).toLowerCase().replace("_", " ");
                newEntries.add(new Entries(word, 0, def));
            }
        }
        int added = 0;
        int nr = 0;
        boolean inList = false;
        for (Entries newE : newEntries) {
            for (Entries e : entries) {
                if (newE.getWord().equals(e.getWord())) {
                    inList = true;
                }
            }
            if (inList == false) {
                String def = newE.getDefinition();
                String word = newE.getWord();
                insertData(nr, word, def);
            } else {
                inList = false;
            }
        }
        TreeSet<Entries> newList = new TreeSet<Entries>(getHQLQuery(QUERY_FULL));
        for (Entries nList : newList) {
            nr++;
            updateHQLQuery(UPDATE_NR, nr, nList.getWord());
        }

        addedlbl.setText("Words added: " + added);
        totalWordslbl.setText("Total words: " + entries.size());
        updateTable();
    }//GEN-LAST:event_addToDictActionPerformed

    private void introTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_introTextMouseClicked
        ContextMenuMouseListener contextMenuMouseListener = new ContextMenuMouseListener();
        contextMenuMouseListener.mouseClicked(evt);
    }//GEN-LAST:event_introTextMouseClicked

    private void getDBdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getDBdataMouseClicked
        try {
            Connection cn = connectToDBbugflow();
            String querySelect = "SELECT column_name FROM information_schema.columns;";
            ArrayList<String> columns = new ArrayList<String>();
            Statement stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery(querySelect);
            while (rs.next()) {
                columns.add(rs.getString(1));
            }
            for (int i = 0; i < columns.size(); i++) {
                introText.append(columns.get(i) + "\r\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_getDBdataMouseClicked

    private void updateTablebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTablebtnMouseClicked
        updateTable();
    }//GEN-LAST:event_updateTablebtnMouseClicked

    private void tableInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInMouseClicked
        ContextMenuMouseListener contextMenuMouseListener = new ContextMenuMouseListener();
        contextMenuMouseListener.mouseClicked(evt);
    }//GEN-LAST:event_tableInMouseClicked

    private void deleteAllbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAllbtnMouseClicked
        updateHQLQuery(DELETE_QUERY_FULL, 0, "");
        updateTable();
    }//GEN-LAST:event_deleteAllbtnMouseClicked

    private void tableInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableInKeyReleased
        /*int key = evt.getKeyCode();
        if(key==KeyEvent.VK_ENTER){
            for (int i = 1; i < table.getRowCount(); i++) {
                updateHQLQuery(UPDATE_DESC, i, table.getValueAt(i, 2).toString());
            }
        }*/
    }//GEN-LAST:event_tableInKeyReleased

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        int key = evt.getKeyCode();
        if(key==KeyEvent.VK_ENTER){
                int row = table.getSelectedRow();
                int col= table.getSelectedColumn();
                String value= (String)table.getValueAt(row, col);
                int nr = (Integer)table.getValueAt(row, 0);
                updateHQLQuery(UPDATE_DESC, nr, value);
        }
    }//GEN-LAST:event_tableKeyReleased

    public void outputTableConf() {
        Font font = new Font("Calibri", Font.PLAIN, 14);

        table.getColumnModel().getColumn(0).setMinWidth(30);
        table.getColumnModel().getColumn(0).setPreferredWidth(30);
        table.getColumnModel().getColumn(0).setMaxWidth(30);
        table.setFont(font);
        table.getColumnModel().getColumn(1).setMinWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setMaxWidth(150);
        table.getColumnModel().getColumn(2).setMinWidth(100);
        table.getColumnModel().getColumn(2).setPreferredWidth(100);
        table.getColumnModel().getColumn(2).setMaxWidth(150);
        table.getColumnModel().getColumn(0).setResizable(false);
    }

    private ListTableModel getTableModel() {
        try {
            List list = getHQLQuery(QUERY_FULL);
            ArrayList<String> colName = new ArrayList<String>();
            colName.add("n");
            colName.add("Word");
            colName.add("Definition");
            ListTableModel model = ListTableModel.createModelFromHQL(list, colName);
            return model;
        } catch (SQLException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }

    }

    private void updateTable() {
        table.setModel(getTableModel());
        outputTableConf();
    }

    private Image getIcon() {
        try {
            return ImageIO.read(getClass().getResource("/res/icon.jpg"));
        } catch (IOException ex) {
            return null;
        }
    }

    public static Connection connectToDBbugflow() {
        Connection connection = null;
        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Where is your PostgreSQL JDBC Driver? "
                    + "Include in your library path!");
        }
        try {
            connection = DriverManager.getConnection(
                    "jdbc:postgresql://localhost/bugflow2", "postgres",
                    "postgres");
        } catch (SQLException e) {
            System.out.println("Connection Failed! Check output console");
        }
        return connection;
    }
    private static String QUERY_FULL = "from Entries";
    private static String DELETE_QUERY_FULL = "DELETE FROM Entries";
    private static String UPDATE_NR = "UPDATE Entries set n = :nr "+ 
             "WHERE word = :word";
    private static String UPDATE_DESC = "UPDATE Entries set definition = :def "+ 
             "WHERE n = :nr";

    private void updateHQLQuery(String hql, int nr, String text) {
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(hql);
            if (hql.equals(UPDATE_NR)) {
                q.setParameter("nr", nr);
                q.setParameter("word", text);
            }
            if (hql.equals(UPDATE_DESC)) {
                q.setParameter("nr", nr);
                q.setParameter("def", text);
            }
            q.executeUpdate();
            session.getTransaction().commit();
        } catch (HibernateException he) {
            he.printStackTrace();
        }
    }

    private List getHQLQuery(String hql) {
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(hql);
            return q.list();
        } catch (HibernateException he) {
            he.printStackTrace();
            return null;
        }
    }

    private void insertData(int n, String word, String def) {
        Session sess = HibernateUtil.getSessionFactory().openSession();
        sess.beginTransaction();
        Entries entry = new Entries(word, n, def);
        sess.save(entry);
        System.out.println("Successfully data insert in database");
        sess.getTransaction().commit();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton addToDict;
    private javax.swing.JLabel addedlbl;
    private javax.swing.JPopupMenu contextMenuPop;
    private javax.swing.JButton deleteAllbtn;
    private javax.swing.JButton getDBdata;
    private javax.swing.JTextArea introText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table;
    private javax.swing.JTable tableIn;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JLabel totalWordslbl;
    private javax.swing.JButton updateTablebtn;
    // End of variables declaration//GEN-END:variables
}
