package dict.entity;
// Generated 2013-11-26 09:53:46 by Hibernate Tools 3.2.1.GA

import java.util.TreeSet;


/**
 * Entries generated by hbm2java
 */
public class Entries implements java.io.Serializable, Comparable<Entries> {

    private String word;
    private Integer n;
    private String definition;

    public Entries() {
    }

    public Entries(String word) {
        this.word = word;
    }

    public Entries(String word, Integer n, String definition) {
        this.word = word;
        this.n = n;
        this.definition = definition;
    }

    public String getWord() {
        return this.word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public Integer getN() {
        return this.n;
    }

    public void setN(Integer n) {
        this.n = n;
    }

    public String getDefinition() {
        return this.definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    @Override
    public int compareTo(Entries o) {
        int last = this.word.compareTo(o.word);
        return last == 0 ? this.word.compareTo(o.word) : last;
    }

    public boolean compareTo(TreeSet<Entries> entries) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
